# Incluindo o pandas

In [2]:
import pandas as pd

# Criar dicionário e converter para um dataframe

In [3]:
#Criando um dicionário
dados = {
   'Nome': ['Alice', 'Bruno','Carlos','Daniela'],
   'Idade':[25, 20, 22, 27],
   'Salário':[3000, 4500, 2500, 5200]
}
print(dados)

{'Nome': ['Alice', 'Bruno', 'Carlos', 'Daniela'], 'Idade': [25, 20, 22, 27], 'Salário': [3000, 4500, 2500, 5200]}

In [4]:
df = pd.DataFrame(dados)
df

      Nome  Idade  Salário
0    Alice     25     3000
1    Bruno     20     4500
2   Carlos     22     2500
3  Daniela     27     5200

In [8]:
df.iloc[2]['Nome']

'Carlos'

# Importando um csv

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/rodrigoh/ciencia-dados/refs/heads/master/a5/datasets/streaming_preferences.csv')
df

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
0,U1000,34,Japan,Tidal,Reggae,295,138,Adele,Free,Afternoon,47.42,16.74
1,U1001,24,Germany,Deezer,Country,86,388,Ed Sheeran,Premium,Night,12.06,69.25
2,U1002,49,Germany,Deezer,Pop,363,368,Post Malone,Premium,Afternoon,47.19,67.38
3,U1003,55,Australia,YouTube,Reggae,348,349,Dua Lipa,Premium,Morning,31.27,76.51
4,U1004,13,Germany,Amazon Music,Reggae,30,328,Adele,Free,Night,30.68,43.41
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,U5995,60,UK,Deezer,Country,348,81,Post Malone,Premium,Morning,49.23,22.36
4996,U5996,38,Australia,Deezer,Hip-Hop,225,218,BTS,Premium,Night,17.08,58.23
4997,U5997,27,Brazil,Amazon Music,Metal,568,277,Taylor Swift,Premium,Night,69.39,51.71
4998,U5998,58,Canada,Amazon Music,EDM,523,492,Bad Bunny,Premium,Night,43.44,24.53
4999,U5999,30,South Korea,YouTube,Rock,451,145,Adele,Premium,Night,15.45,79.46

In [17]:
df = pd.read_excel('C:/Users/rodrigo/Downloads/streaming_preferences.xlsx',sheet_name='pagina_um')
df

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
0,U1000,34,Japan,Tidal,Reggae,295,138,Adele,Free,Afternoon,47.42,16.74
1,U1001,24,Germany,Deezer,Country,86,388,Ed Sheeran,Premium,Night,2025-06-12 00:00:00,69.25
2,U1002,49,Germany,Deezer,Pop,363,368,Post Malone,Premium,Afternoon,47.19,67.38
3,U1003,55,Australia,YouTube,Reggae,348,349,Dua Lipa,Premium,Morning,31.27,76.51
4,U1004,13,Germany,Amazon Music,Reggae,30,328,Adele,Free,Night,30.68,43.41
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,U5995,60,UK,Deezer,Country,348,81,Post Malone,Premium,Morning,49.23,22.36
4996,U5996,38,Australia,Deezer,Hip-Hop,225,218,BTS,Premium,Night,2025-08-17 00:00:00,58.23
4997,U5997,27,Brazil,Amazon Music,Metal,568,277,Taylor Swift,Premium,Night,69.39,51.71
4998,U5998,58,Canada,Amazon Music,EDM,523,492,Bad Bunny,Premium,Night,43.44,24.53
4999,U5999,30,South Korea,YouTube,Rock,451,145,Adele,Premium,Night,15.45,79.46

In [11]:
# Podemos ver as n primeiras do dataset (caso não especifique ele traz 5 linhas)
df.head()

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
0,U1000,34,Japan,Tidal,Reggae,295,138,Adele,Free,Afternoon,47.42,16.74
1,U1001,24,Germany,Deezer,Country,86,388,Ed Sheeran,Premium,Night,12.06,69.25
2,U1002,49,Germany,Deezer,Pop,363,368,Post Malone,Premium,Afternoon,47.19,67.38
3,U1003,55,Australia,YouTube,Reggae,348,349,Dua Lipa,Premium,Morning,31.27,76.51
4,U1004,13,Germany,Amazon Music,Reggae,30,328,Adele,Free,Night,30.68,43.41

In [21]:
df.tail(10)

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
4990,U5990,32,USA,Amazon Music,EDM,511,136,Bad Bunny,Free,Night,39.58,2025-02-12 00:00:00
4991,U5991,27,South Korea,Spotify,R&B,51,166,Post Malone,Premium,Night,12.41,73.82
4992,U5992,46,UK,Apple Music,Hip-Hop,291,64,The Weeknd,Premium,Afternoon,36.62,78.22
4993,U5993,19,Germany,Tidal,Jazz,344,409,Taylor Swift,Premium,Afternoon,61.33,43.26
4994,U5994,55,Australia,Amazon Music,Classical,222,444,Dua Lipa,Premium,Night,56.49,44.17
4995,U5995,60,UK,Deezer,Country,348,81,Post Malone,Premium,Morning,49.23,22.36
4996,U5996,38,Australia,Deezer,Hip-Hop,225,218,BTS,Premium,Night,2025-08-17 00:00:00,58.23
4997,U5997,27,Brazil,Amazon Music,Metal,568,277,Taylor Swift,Premium,Night,69.39,51.71
4998,U5998,58,Canada,Amazon Music,EDM,523,492,Bad Bunny,Premium,Night,43.44,24.53
4999,U5999,30,South Korea,YouTube,Rock,451,145,Adele,Premium,Night,15.45,79.46

# Verificando o tamanho do dataset

In [12]:
# Obtendo o tamanho do dataset
# Ele devolve uma tupla com a quantidade de linhas e colunas
df.shape

(5000, 12)

## Obtendo algumas informações do dataset

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   User_ID                                   5000 non-null   str
 1   Age                                       5000 non-null   int64
 2   Country                                   5000 non-null   str
 3   Streaming Platform                        5000 non-null   str
 4   Top Genre                                 5000 non-null   str
 5   Minutes Streamed Per Day                  5000 non-null   int64
 6   Number of Songs Liked                     5000 non-null   int64
 7   Most Played Artist                        5000 non-null   str
 8   Subscription Type                         5000 non-null   str
 9   Listening Time (Morning/Afternoon/Night)  5000 non-null   str
 10  Discover Weekly Engagement (%)            5000 non-null   float64
 11  Repeat Song Rate (%)                      5000 non-null   float64
dtypes: float64(2), int64(3), str(7)
memory usage: 468.9 KB

## Mostrando informações do dataset

In [15]:
df.describe()

,Age,Minutes Streamed Per Day,Number of Songs Liked,Discover Weekly Engagement (%),Repeat Song Rate (%)
count,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,36.664000,309.237200,253.51720,50.296464,42.391060
std,13.763844,172.029822,146.36928,23.171936,21.444121
min,13.000000,10.000000,1.00000,10.020000,5.000000
25%,25.000000,161.000000,126.00000,30.147500,24.195000
50%,37.000000,316.000000,254.00000,50.420000,41.960000
75%,49.000000,457.250000,382.00000,70.337500,60.740000
max,60.000000,600.000000,500.00000,89.990000,79.990000

In [16]:
df.describe(include='all')

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
count,5000,5000.000000,5000,5000,5000,5000.000000,5000.00000,5000,5000,5000,5000.000000,5000.000000
unique,5000,NaN,10,6,10,NaN,NaN,10,2,3,NaN,NaN
top,U1000,NaN,Australia,Amazon Music,Reggae,NaN,NaN,Bad Bunny,Premium,Night,NaN,NaN
freq,1,NaN,526,861,532,NaN,NaN,528,2526,1745,NaN,NaN
mean,NaN,36.664000,NaN,NaN,NaN,309.237200,253.51720,NaN,NaN,NaN,50.296464,42.391060
std,NaN,13.763844,NaN,NaN,NaN,172.029822,146.36928,NaN,NaN,NaN,23.171936,21.444121
min,NaN,13.000000,NaN,NaN,NaN,10.000000,1.00000,NaN,NaN,NaN,10.020000,5.000000
25%,NaN,25.000000,NaN,NaN,NaN,161.000000,126.00000,NaN,NaN,NaN,30.147500,24.195000
50%,NaN,37.000000,NaN,NaN,NaN,316.000000,254.00000,NaN,NaN,NaN,50.420000,41.960000
75%,NaN,49.000000,NaN,NaN,NaN,457.250000,382.00000,NaN,NaN,NaN,70.337500,60.740000
max,NaN,60.000000,NaN,NaN,NaN,600.000000,500.00000,NaN,NaN,NaN,89.990000,79.990000

# Descobrindo a quantidade de linhas nulas

In [19]:
df.isnull().sum()

User_ID                                     0
Age                                         0
Country                                     0
Streaming Platform                          0
Top Genre                                   0
Minutes Streamed Per Day                    0
Number of Songs Liked                       0
Most Played Artist                          0
Subscription Type                           0
Listening Time (Morning/Afternoon/Night)    0
Discover Weekly Engagement (%)              0
Repeat Song Rate (%)                        0
dtype: int64

In [20]:
df.nunique()

User_ID                                     5000
Age                                           48
Country                                       10
Streaming Platform                             6
Top Genre                                     10
Minutes Streamed Per Day                     591
Number of Songs Liked                        500
Most Played Artist                            10
Subscription Type                              2
Listening Time (Morning/Afternoon/Night)       3
Discover Weekly Engagement (%)              3687
Repeat Song Rate (%)                        3687
dtype: int64

In [21]:
df['Country'].unique()

<StringArray>
[      'Japan',     'Germany',   'Australia', 'South Korea',          'UK',
      'Brazil',      'Canada',       'India',         'USA',      'France']
Length: 10, dtype: str

In [22]:
df['Country']

0             Japan
1           Germany
2           Germany
3         Australia
4           Germany
           ...
4995             UK
4996      Australia
4997         Brazil
4998         Canada
4999    South Korea
Name: Country, Length: 5000, dtype: str

In [23]:
df[['Country', 'Age']]

          Country  Age
0           Japan   34
1         Germany   24
2         Germany   49
3       Australia   55
4         Germany   13
...           ...  ...
4995           UK   60
4996    Australia   38
4997       Brazil   27
4998       Canada   58
4999  South Korea   30

[5000 rows x 2 columns]

In [24]:
# Pegando uma linhas
df.iloc[50]

User_ID                                          U1050
Age                                                 56
Country                                         France
Streaming Platform                               Tidal
Top Genre                                         Rock
Minutes Streamed Per Day                           225
Number of Songs Liked                              214
Most Played Artist                          The Weeknd
Subscription Type                              Premium
Listening Time (Morning/Afternoon/Night)       Morning
Discover Weekly Engagement (%)                   22.61
Repeat Song Rate (%)                             39.19
Name: 50, dtype: object

In [25]:
df.loc[10,'Country']

'South Korea'

In [26]:
df[df['Age']>30]

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
0,U1000,34,Japan,Tidal,Reggae,295,138,Adele,Free,Afternoon,47.42,16.74
2,U1002,49,Germany,Deezer,Pop,363,368,Post Malone,Premium,Afternoon,47.19,67.38
3,U1003,55,Australia,YouTube,Reggae,348,349,Dua Lipa,Premium,Morning,31.27,76.51
6,U1006,49,Australia,Tidal,Country,547,70,Billie Eilish,Free,Night,11.92,37.75
7,U1007,32,UK,Amazon Music,Classical,98,448,Dua Lipa,Premium,Afternoon,29.48,18.80
...,...,...,...,...,...,...,...,...,...,...,...,...
4992,U5992,46,UK,Apple Music,Hip-Hop,291,64,The Weeknd,Premium,Afternoon,36.62,78.22
4994,U5994,55,Australia,Amazon Music,Classical,222,444,Dua Lipa,Premium,Night,56.49,44.17
4995,U5995,60,UK,Deezer,Country,348,81,Post Malone,Premium,Morning,49.23,22.36
4996,U5996,38,Australia,Deezer,Hip-Hop,225,218,BTS,Premium,Night,17.08,58.23
4998,U5998,58,Canada,Amazon Music,EDM,523,492,Bad Bunny,Premium,Night,43.44,24.53

In [27]:
df[(df['Age']>30) & (df['Country']=='Brazil')]

,User_ID,Age,Country,Streaming Platform,Top Genre,Minutes Streamed Per Day,Number of Songs Liked,Most Played Artist,Subscription Type,Listening Time (Morning/Afternoon/Night),Discover Weekly Engagement (%),Repeat Song Rate (%)
9,U1009,37,Brazil,Spotify,Reggae,514,299,Billie Eilish,Premium,Morning,53.39,46.89
11,U1011,43,Brazil,Spotify,Rock,351,108,Drake,Free,Afternoon,48.15,23.70
22,U1022,40,Brazil,Tidal,Jazz,445,221,Dua Lipa,Premium,Morning,80.53,78.27
23,U1023,42,Brazil,Amazon Music,Rock,547,248,Post Malone,Free,Night,26.03,8.42
25,U1025,53,Brazil,Apple Music,Reggae,87,347,Ed Sheeran,Premium,Afternoon,60.40,10.49
...,...,...,...,...,...,...,...,...,...,...,...,...
4924,U5924,31,Brazil,Tidal,Pop,545,479,Dua Lipa,Free,Afternoon,48.71,68.39
4938,U5938,34,Brazil,Tidal,Rock,435,44,Ed Sheeran,Premium,Morning,25.22,60.95
4947,U5947,35,Brazil,Amazon Music,Classical,171,480,Drake,Premium,Morning,66.12,32.21
4955,U5955,34,Brazil,Apple Music,Hip-Hop,163,108,Post Malone,Free,Morning,62.17,71.06
4983,U5983,45,Brazil,Tidal,Rock,469,485,Adele,Premium,Night,16.16,54.74

In [28]:
df['idade'] = df['Age']*2

In [29]:
df.shape

(5000, 13)

In [31]:
df.drop('idade', axis=1, inplace=True)

In [32]:
df.shape

(5000, 12)

In [33]:
df.drop_duplicates(inplace=True)

In [34]:
df.shape

(5000, 12)